/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr.algebra.view;

import hr.algebra.dal.Repository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.model.Event;
import hr.algebra.model.EventArchive;
import hr.algebra.model.User;
import hr.algebra.parsers.rss.EventParser;
import hr.algebra.session.Session;
import hr.algebra.utilities.JAXBUtils;
import hr.algebra.utilities.MessageUtils;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.io.IOException;
import java.net.MalformedURLException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.xml.bind.JAXBException;
import javax.xml.stream.XMLStreamException;

/**
 * --
 *
 * @author kaish
 */
public class UploadEventsPanel extends javax.swing.JPanel {

    private static final String RSS_URL = "https://www.cedefop.europa.eu/en/publications.rss";

    private User currentUser = Session.getCurrentUser();
    private boolean isAdmin = currentUser.getIsAdmin();

    /**
     * Creates new form UploadArticlesPanel
     */
    public UploadEventsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lsArticles = new javax.swing.JList<>();
        btnUploadEvents = new javax.swing.JButton();
        lbUsername = new javax.swing.JLabel();
        JLabel1 = new javax.swing.JLabel();
        btnDeleteAll = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jScrollPane1.setViewportView(lsArticles);

        btnUploadEvents.setText("Upload Events");
        btnUploadEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadEventsActionPerformed(evt);
            }
        });

        JLabel1.setText("Logged in as");

        btnDeleteAll.setBackground(new java.awt.Color(204, 0, 51));
        btnDeleteAll.setText("Delete All Events");
        btnDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUploadEvents, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUploadEvents, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadEventsActionPerformed

        new Thread(() -> {

            try {

//                ParseEvents();
                JAXBParseEvents();

            } catch (Exception ex) {
                MessageUtils.showErrorMessage("Unrecoverable error", "Unable to upload events: " + ex.getMessage());
                System.exit(1);
            }
        }).start();
    }//GEN-LAST:event_btnUploadEventsActionPerformed

    private void JAXBParseEvents() throws MalformedURLException, JAXBException, Exception {

        // JAXB parsing of RSS feed
        EventArchive eventArchive = JAXBUtils.loadRSS(EventArchive.class, RSS_URL);
        List<Event> events = eventArchive.getChannel().getEvents();
        repository.createEvents(events);
        loadModel();
    }

    private void parseEvents() throws XMLStreamException, IOException, Exception {

        // Regular events parser
        List<Event> events = EventParser.parse();
        repository.createEvents(events);
        loadModel();
    }

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        init();
    }//GEN-LAST:event_formComponentShown

    private void btnDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllActionPerformed

        if (MessageUtils.showConfirmDialog(
                "Delete event",
                "Do you really want to delete all events?")) {
            try {

                deleteAllEvents();
                loadModel(); // Just to make sure current DB is shown (nothing)

            } catch (Exception ex) {
                Logger.getLogger(EditEventsPanel.class.getName()).log(Level.SEVERE, null, ex);
                MessageUtils.showErrorMessage("Error", "Unable to delete events!");
            }
        }
    }//GEN-LAST:event_btnDeleteAllActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JButton btnDeleteAll;
    private javax.swing.JButton btnUploadEvents;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JList<hr.algebra.model.Event> lsArticles;
    // End of variables declaration//GEN-END:variables

    private DefaultListModel<Event> eventsModel;
    private Repository repository;

    private void init() {
        try {
            repository = RepositoryFactory.getRepository();
            eventsModel = new DefaultListModel<>();

            lbUsername.setText(currentUser.getUsername());
            if (isAdmin) {
                lbUsername.setFont(new Font("Segoe UI", Font.BOLD, 12));
            }

            loadModel();
        } catch (Exception ex) {
            Logger.getLogger(UploadEventsPanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Unrecoverable error", "Cannot initiate the form");
            System.exit(1);
        }
    }

    private void loadModel() throws Exception {

        List<Event> events = repository.selectEvents();

        EventQueue.invokeLater(() -> {

            eventsModel.clear();
            events.forEach(eventsModel::addElement);
            lsArticles.setModel(eventsModel);
        });
    }

    private void deleteAllEvents() throws Exception {
        List<Event> events = repository.selectEvents();

        // For some reason using lambda made me try catch, the throws 
        // clause didn't fix the error so I looped like this
        for (Event event : events) {
            repository.deleteEvent(event.getId());
        }

    }

}
